name: flutter_base_project
description: Flutter Base Project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  bloc: ^5.0.0
  flutter_bloc: ^5.0.0
  fluro: ^1.6.3
  logger: ^0.9.1
  built_value: ^7.1.0
  built_collection: ^4.3.2
  dio: ^3.0.9
  dio_log: ^1.3.4
  retrofit: ^1.3.4
  shared_preferences: ^0.5.8
  permission_handler: ^5.0.1+1
  package_info: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  retrofit_generator: ^1.3.7+2

flutter:
  uses-material-design: true
